### ISSUE TITLE
erreur import opml

### ISSUE THREAD

**Issue by emporeso2** [timovn/oText#2]
Bonjour,

j'ai cette erreur lors de l'imporrt d'un opml 

"Warning: Invalid argument supplied for foreach() in /opt/lampp/htdocs/oText/admin/maintenance.php on line 463"

**Comment by emporeso2** [comment]
voici 2 opml qui ne fonctionne pas
https://justpaste.it/5eujy

**Comment by emporeso2** [comment]
test effectué en local sur un lampp !

**Comment by timovn** [comment]
Salut,

Les 2 codes OPML sont invalides pour commencer : https://codebeautify.org/opmlviewer (colles un OPML à gauche puis clics sur "tree view").

Un autre validateur : http://beautifytools.com/opml-minifier.php (il affiche les erreurs à gauche).
