### ISSUE TITLE
oText et yunohost

### ISSUE THREAD

**Issue by mehkera** [timovn/oText#3]
Bonjour,

je voudrais ajouter oText sur un yunohost [https://github.com/YunoHost](url)
lors de l'install oText m'impose d'utiliser mysql ! hors je veux utiliser sqllite !

Comportement normal de l'installation ? ou dois je modifier quelque chose quelque part ?

Merci de votre aide.

**Comment by emporeso2** [comment]
J'ai essyé de modifier le fichier /admin/install pour forcer l'install de sqllite , j'ai ce message 

Erreur 1: could not find driver

**Comment by timovn** [comment]
Il détecte la présence de SQLite à l’installation.
S’il ne le propose pas, c’est que ça n’est pas installé. Il utiliser SQLite au travers de PDO (voir le "readme").
